apiVersion: v1
kind: Service
metadata:
  name: insurance-service
  labels:
    app: insurance
spec:
  ports:
   - name: akash-insurance-container
     port: 8081
     targetPort: 8084
  type: NodePort
  selector:
    app: insurance
    tier: web
